# Generated by Django 4.1 on 2022-10-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_grouppost_who_can_comment_grouppost_who_can_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='allow_connection',
            field=models.BooleanField(default=True, help_text='allow connect to general user'),
        ),
    ]
