# Generated by Django 4.1 on 2022-10-09 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_blocklist_block_friends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='friends',
        ),
        migrations.AddField(
            model_name='user',
            name='block_friends',
            field=models.ManyToManyField(blank=True, related_name='blocked_friend_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BlockList',
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
    ]
