# Generated by Django 4.0.6 on 2022-08-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='BlackListedToken',
        ),
    ]
