# Generated by Django 4.0.6 on 2022-08-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_refresh_token_user_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
